import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./shared/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "As Sunnah Foundation",
  description: "Generated by As Sunnah Foundation",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
